config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: 'users/registrations'}
  
  resources :users do
    resource :profile
  end
  
  resources :contacts
  
  get '/about' => 'pages#about'
  
  root "pages#homepage"
  

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :name, presence: true
  validates :email, presence: true
  validates :comments, presence: true
end

app/models/plan.rb
class Plan < ActiveRecord::Base
  has_many :users
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  
  # From Paperclip GitHub README
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.jpg"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :plan
  has_one :profile
  attr_accessor :stripe_card_token # Allows usage of hidden field value to create customer in Stripe server
  def save_with_payment
    if valid?
      # Charges customer and returns an id for the customer.
      customer = Stripe::Customer.create(description: email, plan: plan_id, card: stripe_card_token)
      # Set user property equal to Stripe's ID
      self.stripe_customer_token = customer.id
      # Save the user
      save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?
  
  
  # Devise documentation
  protected
    # Whitelisting parameters
    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :stripe_card_token, :email, :password, :password_confirmation)}
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end
  
  def create
    @contact = Contact.new(contact_params)
    
    if @contact.save
      name = params[:contact][:name]
      email = params[:contact][:email]
      body = params[:contact][:comments]
      ContactMailer.contact_email(name, email, body).deliver
      flash[:success] = "Message sent"
      redirect_to new_contact_path
    else
      flash[:warning] = "Something went wrong. Message NOT sent."
      redirect_to new_contact_path
    end    
  end
  
  private
    def contact_params
      params.require(:contact).permit(:name, :email, :comments)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def homepage
    @free_plan = Plan.find(1)
    @premium_plan = Plan.find(2)
  end
  
  def about
    
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  
  # Use devise action "authenticate_user" to make a rule
  # that users cannot access ANY page in the profiles
  # controller unless the user is authenticated / has a 
  # valid account.
  before_action :authenticate_user!
  
  # Only the current user should have access to their own
  # pages below and not other users'.
  before_action :only_current_user
  
  def new
    # form for user profile content
    
    # Look in the database and find the user who is logged in.
    @user = User.find(params[:user_id])
    
    # Once the user is found, build a profile for that user
    # using "Profile.new." We're avoiding build_profile
    # because we don't want a new profile created every
    # time a user visits a new profile.
    @profile = Profile.new
  end
  
  def create
    # Look in the database and find the user who is logged in.
    @user = User.find(params[:user_id])
    
    # Once the user is found, build a profile for that user
    # using "build_profile" which is a Rails built-in method.
    # Pass in whatever the user inputs in their profile update
    # form.
    @profile = @user.build_profile(profile_params)
    
    # If everything passes validation and the profile saves,
    if @profile.save
      # Redirect to the user's show page.
      redirect_to user_path(params[:user_id])
    else
      render action: :new 
    end
  end
  
  def edit
    
    # Look in the database and find the user who is logged in.
    @user = User.find(params[:user_id])
    
    # Grab the profile that the user has created.
    @profile = @user.profile
  end
  
  def update
    # Look in the database and find the user who is logged in.
    @user = User.find(params[:user_id])
    
    # Grab the profile that the user has created.
    @profile = @user.profile
    
    if @profile.update_attributes(profile_params)
      # flash[:success] = "Profile updated"
      redirect_to user_path(params[:user_id])
    else
      render action: :edit
    end
  end
  
  # Whitelist the form fields to make them accessible.
  private
    def profile_params
      params.require(:profile).permit(:first_name, :last_name, :job_title, :avatar, :description, :contact_email, :phone_number)
    end
    
    def only_current_user
      # Look in the database and find the user who is logged in.
      @user = User.find(params[:user_id])
      
      # Redirect the user who tries to access a page that is not
      # theirs.
      redirect_to(root_url) unless @user == current_user
    end
end

app/controllers/users/registrations_controller.rb
# This file overrides Devise's default parameters.
class Users::RegistrationsController < Devise::RegistrationsController
  # Run the filter function select_plan before any of the code below is run.
  before_filter :select_plan, only: :new
  
  
  def create
    # Import create action code
    super do |resource|
  
      # When user submits either form, grab the form and check to see
      # if a parameter plan is in there (it should be).
      if params[:plan]
  
        # if so, save that value inside resource.plan_id.
        resource.plan_id = params[:plan]
  
        # Then if the plan id of the user is the premium option,
        if resource.plan_id === 2
  
          # then save that form while keeping in mind user's plan_id
          # and then charge their account for payment. save_with_payment
          # is defined in user.db under models.
          resource.save_with_payment
        else
  
          # if they have the free account, save as usual.
          resource.save
        end
      end
    end
  end
  
  private
    # This function is to prevent a user from entering in an 
    def select_plan
      unless params[:plan] && (params[:plan] == '1' || params[:plan] == '2')
        redirect_to root_url
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  # Use devise action "authenticate_user" to make a rule
  # that users cannot access ANY page in the profiles
  # controller unless the user is authenticated / has a 
  # valid account.
  before_action :authenticate_user!
  
  def index
    # Create a users variable and store all users in it.
    @users = User.all
  end
  
  def show
    # Show the user profile of the particular user.
    @user = User.find(params[:id] )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  # Define an icon for each user-type
  def job_title_icon
    if @user.profile.job_title === "Developer"
      "<i class='fa fa-code'></i>".html_safe
    elsif @user.profile.job_title === "Employer"
      "<i class='fa fa-user'></i>".html_safe
    elsif @user.profile.job_title === "Entrepreneur"
      "<i class='fa fa-briefcase'></i>".html_safe
    elsif @user.profile.job_title === "Hobbyist"
      "<i class='fa fa-clock-o'></i>".html_safe
    elsif @user.profile.job_title === "Recruiter"
      "<i class='fa fa-user'></i>".html_safe
    end
  end
end

app/views/contacts/new.html.erb
<div class = "jumbotron contacts">
    <div class="container">
        <div class = "row">
            <div class = "col-md-4 col-md-offset-4">
                <div class="well contact-padding contact-form-border">
                    <%= form_for @contact do |f| %>
                        NOTE: Messaging disabled to avoid Heroku charges.
                        <br>
                        <div class="form-group">
                            <%= f.label :name %>
                            <%= f.text_field :name, class: 'form-control form-dimensions-contact', placeholder: "Enter name" %>
                        </div>
                        
                        <div class="form-group">
                            <%= f.label :email %>
                            <%= f.email_field :email, class: 'form-control form-dimensions-contact', placeholder: "Enter email" %>
                        </div>
                        
                        <div class="form-group">
                            <%= f.label :comments %>
                            <%= f.text_area :comments, class: 'form-control', placeholder: "Enter message" %>
                        </div>
                        
                        <%= f.submit 'Submit', class: 'btn btn-default' %>
                        
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Light Bulb</title>
  
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  
  <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Lobster+Two', media: 'all', 'data-turbolinks-track' => true %>
  <!--<%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Roboto', media: 'all', 'data-turbolinks-track' => true %>-->
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag "https://js.stripe.com/v2/", type: 'text/javascript' %>
  <%= javascript_include_tag 'application' %>
  <%= tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY %>
  <%= csrf_meta_tags %>
  
</head>
<body>
<div class="navbar transparent navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      
      <% if controller_name === "pages" && action_name === "homepage" %>
        <%= link_to root_path, class: 'navbar-brand nav-font' do %>
          Light<i class="fa fa-lightbulb-o" id="fa-size"></i>Bulb
        <% end %>
      <% else %>
        <%= link_to root_path, class: 'navbar-brand nav-font-inverted' do %>
          Light<i class="fa fa-lightbulb-o" id="fa-size"></i>Bulb
        <% end %>
      <% end %>  
        
    </div>  
    <div class="collapse navbar-collapse" id="main-nav-collapse">
      <div class = "nav navbar-nav navbar-right">
        <% if current_user %>
          <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-primary navbar-btn" %>
        <% else %>
          <%= link_to "Log In", new_user_session_path, class: "btn btn-primary navbar-btn", method: :get %>
        <% end %>
      </div>
      
      <% if controller_name === "pages" && action_name === "homepage" %>
          <ul class="nav navbar-nav navbar-right nav-font">
      <% else %>
          <ul class="nav navbar-nav navbar-right nav-font-inverted">
      <% end %>
        
        <% if current_user && current_user.profile %>
          <li><%= link_to "Profile", user_path(current_user) %><li>
          <% if current_user.profile %>
            <li><%= link_to "Club", users_path %></li>
          <% end %>
        <% end %>  
        
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Contact", new_contact_path %></li>
      </ul>
    </div>
  </div>
</div>  


<% if controller_name === "pages" && action_name === "homepage" %>
  <%= yield %>
<% elsif controller_name === "pages" && action_name === "contacts" %>
    <% flash.each do |key, value| %>
      <br><br><br><br><br>
      <%= content_tag :div, value, class: "alert alert-#{key}" %>
    <% end %>
  <%= yield %>
<% else %>  
    <%= yield %>
<% end %> 

</body>
</html>

app/views/pages/about.html.erb
<div class="jumbotron show-page-user">
    <div class="container">
        <div class="row">
            <div class = "col-md-8 col-md-offset-2">
                <div class="well contact-form-border text-center" id="about-padding">
                    <h1 id="about-title">About</h1>
                    <p>Light Bulb is a responsive, Ruby on Rails job post search service that gives users a platform to sign up and put themselves out there. Users can use the application to search for employees, find great people to work for, or even find or come up with project ideas with the aim of collaborating with other interested users to form teams. Light Bulb is a subscription-based service, but users can still use the application free of charge. For a small monthly fee, the subscription model allows subscribers to view the contact information that users have provided in their profile to get in touch with them. Free users cannot see other users' contact information. The application has been fully configured to handle monthly payments through the Stripe API.</p>
                </div>
            </div>
        </div>
    </div>
</div>    

app/views/pages/homepage.html.erb
<div class="jumbotron homepage text-center">
    <div class="container">
        <div class="row">
            <br>
            <% if current_user %>
                <br>
                <h1 id="lightbulb-greeting">Light Bulb</h1>
                <p id="lightbulb-greeting-start">Bring your ideas to light.</p>
                <% if current_user.profile %>
                    <%= link_to "Visit the Club", users_path, class: "btn btn-default" %>
                <% elsif current_user %>
                    <%= link_to "Create Your Profile to Access the Club", new_user_profile_path(current_user), class: "btn btn-default" %>
                <% end %>    
            <% else %>
                <div>
                    <div id="plans-positioning">
                        <div class="col-md-6">
                            <div class="well contact-form-border">
                                <h3 class="text-center">Free Membership</h3>
                                <h4>Sign up for a free account to get a feel for the site and basic Club access to view everyone's ideas. You must sign up for an account in order to enter the Club.</h4>
                                <%= link_to "Go Free", new_user_registration_path(plan: @free_plan.id), class: "btn btn-primary btn-lg btn-block" %>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="well contact-form-border">
                                <h3 class="text-center">Premium Membership</h3>
                                <h4>For $2 per month, go premium to have the same access as free user, but also see all users' preferred contact information to make it easy to get in touch with them.</h4>
                                <%= link_to "Go Premium", new_user_registration_path(plan: @premium_plan.id), class: "btn btn-success btn-lg btn-block" %>
                            </div>
                        </div>
                    </div>
                </div>    
            <% end %>
        </div>
    </div>
</div>

app/views/profiles/_form.html.erb
<%= form_for @profile, url: user_profile_path, html: { multipart: true } do |form| %>

    <div class="form-group">
        <%= form.label :first_name %>
        <%= form.text_field :first_name, class: "form-control" %>
    </div>

    <div class="form-group">
        <%= form.label :last_name %>
        <%= form.text_field :last_name, class: "form-control" %>
    </div>

    <div class="form-group">
        <%= form.label :job_title %>
        <%= form.select :job_title, [['Select Job Title', {disabled: 'disabled'}], 'Developer', 'Employer', 'Entrepreneur', 'Hobbyist', 'Recruiter'], {}, class: "form-control" %>
    </div> 
    
    <div class="form-group">
        <%= form.label :avatar %>
        <%= form.file_field :avatar, class: "form-control" %>
    </div>    

    <div class="form-group">
        <%= form.label :description %>
        <%= form.text_area :description, class: "form-control" %>
    </div>        

    <div class="form-group">
        <%= form.label :contact_email %>
        <%= form.text_field :contact_email, class: "form-control" %>
    </div>  

    <div class="form-group">
        <%= form.label :phone_number %>
        <%= form.text_field :phone_number, class: "form-control" %>
    </div>  

    <div class="form-group">
        <%= form.submit "Update", class: "btn btn-primary" %>
    </div>
    
<% end %>

app/views/profiles/edit.html.erb
<br><br><br><br>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center">Edit Profile</h1>
        <p class="text-center">Please note that profile pictures have been disabled to avoid Amazon charges.</p>
        <div class="well">
            <%= render 'form' %>
        </div>
    </div>
</div>

app/views/profiles/new.html.erb
<br><br><br><br>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center">Create Your Profile</h1>
        <p class="text-center">Please note that profile pictures have been disabled to avoid Amazon charges.</p>
        <div class="well">
            <%= render 'form' %>
        </div>
    </div>
</div>

app/views/users/index.html.erb
<br><br><br><br><br>
<div class="col-md-8 col-md-offset-2">
    <!--<div class="container">-->
    <h1 class="text-center" id="club-header">Welcome to the Club!</h1>
        <ul class="list-unstyled no-text-dec">
            <% @users.each do |user| %>
                <% if user.profile %>
                    <%= link_to(user, class: 'no-text-dec') do %>
                    <li>
                        <div class="well row contact-form-border no-text-dec">
                            <div class="col-sm-4 text-center">
                                
                                    <%#= image_tag user.profile.avatar.url %><br>
                                    <%= image_tag("missing.jpg", :alt => "Missing") %>
                                
                            </div>
                            <div class="no-text-dec">
                                
                                    <h2><%= user.profile.first_name %> <%= user.profile.last_name %></h2>
                                    
                                <p><%= user.profile.job_title %></p>
                            </div>
                        </div>
                    </li>    
                    <% end %>
                <% end %>
            <% end %>
        </ul>
    <!--</div>-->
</div>

app/views/users/show.html.erb
<div class="jumbotron show-page-user">
  <div class="container">
    <div class="row">
        <div class = "col-md-8 col-md-offset-2">
            <div class="well contact-padding contact-form-border">
              
              <a href="<%= edit_user_profile_path(user_id: current_user.id) %>"><i class="fa fa-pencil-square-o fa-2x pull-right"></i></a>
              <div class="container intro-position text-center">
                  <%= image_tag("missing.jpg", :alt => "Missing", class: "img-style") %>
                  <%#= image_tag @user.profile.avatar.url %>
                  <h1 id="somea"><%= @user.profile.first_name %> <%= @user.profile.last_name %></h1>
                  <h3><span id="job-span"><span id="job-icon"><%= job_title_icon %></span> <%= @user.profile.job_title %></span></h3>
              </div>  
              <h4>About Me:</h4> <%= @user.profile.description %>
              <% if current_user.plan_id == 2 %>
                <h4>My Preferred Email:</h4><%= @user.profile.contact_email %><br>
                <h4>My Preferred Phone Number:</h4><%= @user.profile.phone_number %><br>
              <% end %>
            </div>
          </div>  
      </div>
  </div>
</div>